In [2]:
import pandas as pd

Read csv files

In [46]:
path = '../../data/curated/min_distance/'
filename = '_min_distance.csv'
COL = ['address', 'postcode', 'SA2_CODE', 'residence_type', 
        'nbed', 'nbath', 'ncar', 'weekly_rent', 'dist_to_cbd_KM', 
        'min_distance_to_park', 'min_distance_to_prim', 'min_distance_to_second', 
        'min_distance_to_train', 'min_distance_to_hosp', 'min_distance_to_poli', 'min_distance_to_shop']
# 'year', 'month', 'latitude_ori', 'longitude_ori',

rent = {}
for y in range(2013, 2023):
    rent[str(y)] = pd.read_csv('../../data/curated/min_distance/'+str(y)+filename)
    #rent[str(y)] = rent[str(y)][COL]

In [48]:
rent['2018']

,address,nbed,nbath,ncar,postcode,SA2_CODE,residence_type,dist_to_cbd_KM,min_distance_to_park,min_distance_to_prim,min_distance_to_second,min_distance_to_train,min_distance_to_hosp,min_distance_to_poli,min_distance_to_shop,weekly_rent
0,"- GOUGHS BAY ROAD, GOUGHS BAY",3.0,2.0,2,3723,204011057,House,223.34625,14.19398,16.43158,16.81052,30.94288,16.72488,17.42122,NaN,320.00
1,". 'WILLOW COTTAGE' TARCOMBE RD, AVENEL",3.0,1.0,1,3664,204011058,House,126.11110,18.37700,9.08981,NaN,10.60099,NaN,28.86936,NaN,250.00
2,". 'WILLOW COTTAGE' TARCOMBE ROAD, AVENEL",3.0,1.0,1,3664,204011058,House,127.42434,19.69024,10.40304,NaN,11.91423,NaN,30.18259,NaN,250.00
3,". SHERBROOK LODGE ROAD, PORT CAMPBELL",3.0,1.0,0,3269,217031475,House,229.04370,0.31195,32.25031,38.45370,17.06491,17.47880,0.04991,NaN,500.00
4,". U0027WILLOW COTTAGEU0027 TARCOMBE ROAD, AVENEL",3.0,1.0,1,3664,204011058,House,126.11110,18.37700,9.08981,NaN,10.60099,NaN,28.86936,NaN,250.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14203,"UNITS 1-11/279 WYNDHAM STREET, SHEPPARTON",1.0,1.0,0,3630,216031416,Apartment,180.70817,1.79496,1.63542,1.63417,NaN,2.31499,NaN,NaN,200.00
14204,"VICTORY AVENUE, FOSTER",1.0,1.0,1,3960,205031087,Apartment,173.14283,1.14346,1.11816,0.48686,1.91073,1.38101,0.66149,NaN,131.25
14205,"VILLA 6/1-5 CANAL ROAD, PAYNESVILLE",3.0,1.0,1,3880,205021086,House,293.28053,0.56012,1.21809,NaN,NaN,NaN,NaN,NaN,265.00
14206,"WELSHPOOL ROAD, TOORA",4.0,1.0,1,3962,205031087,House,184.60923,10.42480,0.35078,13.33215,1.72282,14.08709,1.17250,NaN,295.00
14207,"WOORARRA ROAD, WELSHPOOL",3.0,1.0,4,3966,205031087,House,196.40150,8.80920,8.76518,25.12441,8.36026,25.87935,13.03930,NaN,250.00