In [4]:
import pandas as pd 
import numpy as np

def liveability():
    df = pd.read_csv('../data/curated/merged_dataset/2022_merged_data.csv')
    weight = [1/9, 1/9, 1/9,1/9, 1/9, 1/9,1/9, 1/9, 1/9]
    COLS = ["address","sa2_2021",
        'min_distance_to_poli', 'crime_cases',  'min_distance_to_prim',
       'min_distance_to_second', 'min_distance_to_train',
       'min_distance_to_hosp','min_distance_to_park',
       'min_distance_to_cbd', 'min_distance_to_shop']
    COL = [
        'min_distance_to_poli', 'crime_cases',  'min_distance_to_prim',
       'min_distance_to_second', 'min_distance_to_train',
       'min_distance_to_hosp','min_distance_to_park',
       'min_distance_to_cbd', 'min_distance_to_shop']
    ranking = pd.DataFrame()
    for col in COLS:
        if col not in ["address","sa2_2021"]:
            ranking[col] = df[col].rank(ascending=False)
        else:
            ranking[col] = df[col]
    for col in COL:
        if col not in ["address","sa2_2021"]:
            ranking[col] = ranking[col]/len(ranking[col])
    score = ranking
    def liveability_scoring(scores, cols, weights):
        """Takes score data, list of weights and column names, return the total liveability score based on the weights"""
        # check the validation of weight list
        if len(weights) != len(cols):
            return np.nan
        if sum(weights) != 1:
            return np.nan
        
        # initialize the values
        scores["total_liveability_score"] = 0

        # calculate the total liveability
        for i, rows in scores.iterrows():
            list_sum = 0
            for n in range(0, len(cols)):
                if not np.isnan(scores.loc[i, cols[n]]):
                    list_sum = list_sum + (scores.loc[i, cols[n]]*weights[n])
            scores.loc[i, "total_liveability_score"] = list_sum
        return scores
    total_score = liveability_scoring(score, COL, weight)
    total_score =total_score.sort_values(by=['total_liveability_score'], ascending=False)
    result = total_score.address.head(10)
    return result

In [9]:
df = pd.read_csv('../data/curated/merged_dataset/2022_merged_data.csv')
weight = [1/9, 1/9, 1/9,1/9, 1/9, 1/9,1/9, 1/9, 1/9]
COLS = ["address","sa2_2021",
    'min_distance_to_poli', 'crime_cases',  'min_distance_to_prim',
    'min_distance_to_second', 'min_distance_to_train',
    'min_distance_to_hosp','min_distance_to_park',
    'min_distance_to_cbd', 'min_distance_to_shop']
COL = [
    'min_distance_to_poli', 'crime_cases',  'min_distance_to_prim',
    'min_distance_to_second', 'min_distance_to_train',
    'min_distance_to_hosp','min_distance_to_park',
    'min_distance_to_cbd', 'min_distance_to_shop']
ranking = pd.DataFrame()
for col in COLS:
    if col not in ["address","sa2_2021"]:
        ranking[col] = df[col].rank(ascending=False)
    else:
        ranking[col] = df[col]
for col in COL:
    if col not in ["address","sa2_2021"]:
        ranking[col] = ranking[col]/len(ranking[col])
score = ranking

In [19]:
score

,address,sa2_2021,min_distance_to_poli,crime_cases,min_distance_to_prim,min_distance_to_second,min_distance_to_train,min_distance_to_hosp,min_distance_to_park,min_distance_to_cbd,min_distance_to_shop
0,"(UPSTAIRS) 1/578 BARKLY STREET, WEST FOOTSCRAY",213031351,0.059853,0.299639,0.823103,NaN,0.268800,NaN,0.578141,0.836437,NaN
1,". 'WILLOW COTTAGE' TARCOMBE RD, AVENEL",204011058,0.002067,0.993259,0.008250,NaN,0.021416,NaN,0.004954,0.133655,NaN
2,". 'WILLOW COTTAGE' TARCOMBE ROAD, AVENEL",204011058,0.001751,0.993259,0.006984,NaN,0.018325,NaN,0.004488,0.131886,NaN
3,". GLYNDON ROAD, CAMBERWELL",207011149,0.078197,0.680724,0.449216,0.201656,0.332284,NaN,0.859753,0.713136,NaN
4,". SHERBROOK LODGE ROAD, PORT CAMPBELL",217031475,0.472420,0.998724,0.000410,0.002104,0.010689,0.009777,0.843663,0.050933,NaN
...,...,...,...,...,...,...,...,...,...,...,...
53693,"VILLA 6/1-5 CANAL ROAD, PAYNESVILLE",205021086,NaN,0.944011,0.367649,NaN,NaN,NaN,0.685463,0.029908,NaN
53694,"WANGOOM ROAD, WARRNAMBOOL",217041479,NaN,0.211982,0.018958,0.086130,0.025830,0.083132,0.061473,0.040095,NaN
53695,"WILKS, CAULFIELD NORTH",208021177,NaN,0.784275,0.314611,0.377407,0.081698,NaN,0.120433,0.826921,0.070952
53696,"WRECKYN STREET, NORTH MELBOURNE",206041506,NaN,0.410490,0.424522,0.482625,0.249674,NaN,0.626699,0.988845,NaN
53697,"Y112/125 TURNER STREET, ABBOTSFORD",206071139,0.280085,0.541389,0.812432,0.422697,0.369958,NaN,0.739190,0.950277,NaN

In [24]:
def liveability_scoring(scores, cols, weights):
    """Takes score data, list of weights and column names, return the total liveability score based on the weights"""

    # initialize the values
    scores["total_liveability_score"] = 0

    # calculate the total liveability
    for i, rows in scores.iterrows():
        list_sum = 0
        for n in range(0, len(cols)):
            if not np.isnan(scores.loc[i, cols[n]]):
                list_sum = list_sum + (scores.loc[i, cols[n]]*weights[n])
        scores.loc[i, "total_liveability_score"] = list_sum
    return scores

In [25]:
weight

[0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111]

In [26]:
total_score = liveability_scoring(score, COL, weight)

In [45]:
result = total_score.address.head(10)

In [46]:
list(result)

['(UPSTAIRS) 1/578 BARKLY STREET, WEST FOOTSCRAY',
 ". 'WILLOW COTTAGE' TARCOMBE RD, AVENEL",
 ". 'WILLOW COTTAGE' TARCOMBE ROAD, AVENEL",
 '. GLYNDON ROAD, CAMBERWELL',
 '. SHERBROOK LODGE ROAD, PORT CAMPBELL',
 '.1 AIRLEY COURT, MEADOW HEIGHTS',
 '.11 CUMBERLAND AVENUE, WARRAGUL',
 '.2148 LARDNERS TRACK, TETOORA ROAD',
 '.25 GAUL AVENUE, DARNUM',
 '.4 MYRTLE STREET, CAMPBELLFIELD']

In [39]:
result[1]

". 'WILLOW COTTAGE' TARCOMBE RD, AVENEL"

In [43]:
s = pd.Series(result,
              name="address")
s.to_frame()
s.iloc[1]

". 'WILLOW COTTAGE' TARCOMBE RD, AVENEL"